es-ES:
  message-0: "[Currencies]: La moneda "
  message-0_1: "se ha creado"
  message-1: "[Currencies]: tú moneda se ha suprimido"
  message-1_1: "[Currencies]: tú moneda se ha suprimido y no se donaran minerales"
  message-2: "[Currencies]: Has acuñado"
  message-3: "[Currencies]: Depositado "
  message-3_1: " unidades de valor de los minerales en tú moneda"
  message-4: "[Currencies]: Pagó "
  message-4_1: "[Currencies]: Recibido "
  message-4_2: "[Currencies]: a "
  message-4_3: "[Currencies]: de "
  message-5: "[Currencies]: Retiraste"
  message-6: "[Currencies]: Descripción definida"
  message-7: "| Ascecia Currencies | Ayuda | \n \n /currencies create (nombre) - crear una moneda \n /currencies delete (nombre) - supprimir una moneda \n /currencies witdraw (nombre) (cantidad) - Retirar alguna cantidad de moneda \n /currencies info (nombre) - Información sobre una moneda \n /currencies list - Lista de las monedas \n /currencies mint (cantidad) - acuñar alguna cantidad de moneda \n /currencies deposit - Depositar las minerales que son en tú mano \n /currencies pay (nombre del jugador) (nombre de la moneda) (cantidad) - Pagar una cantidad de moneda a una otra persona \n /currencies wallet - muestra tú cartera \n /currencies top (all/one) (si one: nombre) - El clasificación de los que son más ricos"
  message-8: "\n | Ascecia-Currencies | Moneda info -> | "
  message-8_1: " | \n \n Cantidad de moneda en circulación: "
  message-8_2: "\n Potencia de la moneda: "
  message-8_3: "\n Número de usuarios: "
  message-8_4: "\n Actividad económica de la moneda:"
  message-8_5: "\n Valor de la moneda: "
  message-8_6: "\n Autor: "
  message-8_7: "\n Descripción: "
  message-9: "\n | Ascecia-Currencies | Lista de las monedas | \n \n"
  message-9_1: "\n      Potencia: "
  message-9_2: "\n      Actividad económica: "
  message-10: "\n | Ascecia-Currencies | Carrera | \n"
  message-10_1: "\n      Saldo: "
  message-11: "Se ha Renombrada a "
  message-12: "[Currencies]: Configuración Recargada !"
  message-13: "| Ascecia Currencies | Top | "
  message-14: "[Currencies]: Idioma definida !"
