es-ES:
  message-0: "not yet implemented"
  message-0_1: "se ha creado"
  message-1: "not yet implementedse ha suprimido"
  message-1_1: "not yet implementedse ha suprimido y no se donaran minerales"
  message-2: "not yet implemented"
  message-3: "not yet implemented"
  message-4: "not yet implemented"
  message-5: "not yet implemented"
  message-6: "not yet implemented"
  message-7: "not yet implemented"
  message-8: "not yet implemented"
  message-9: "not yet implemented"
  message-10: "not yet implemented"
  message-11: "not yet implemented"
  message-12: "not yet implemented"
  message-13: "not yet implemented"
  message-14: "not yet implemented"