name: AsceciaCurrencies
version: '${project.version}'
main: me.rgn.asceciacurrencies.AsceciaCurrencies
api-version: 1.19
authors: [ RGn2 ]
description: Ascecia Currencies is a plugin that allow new currencies to be made
website: https://panascecia.duckdns.org
commands:
  currencies:
    description: The core command
    usage: /<command> <subcommand>
