name: AsceciaCurrencies
version: '1.3-Release-Candidate'
main: me.rgn.asceciacurrencies.AsceciaCurrencies
authors: [ RGn2 ]
api-version: 1.13
description: Ascecia Currencies is a plugin that allow new currencies to be made
website: https://panascecia.duckdns.org
commands:
  currencies:
    description: The core command
    usage: /<command> <subcommand>
    aliases: [c, cu]
softdepend:
  - Medieval-factions
permissions:
  ascecia:
    player:
      manage:
      mint:
      deposit:
      withdraw:
      infos:
      wallet:
      rename:
      top:
      team:
      pay:
      convert:
    admin:
      forcemanage:
      reload-config:
      language:
      ore: